[package]
name = "haversine"
version = "0.1.1"
authors = ["Adam Shirey <adam@shirey.ch>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
